version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"  # Serve on public port 80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
