apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: model
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 8002
      protocol: TCP
      targetPort: 8002
  type: ClusterIP